name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the
        existing and past issues](https://github.com/meta-llama/synthetic-data-kit/issues).

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system information
      placeholder: |
        Python version, OS, package version...
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.
        Please also paste or describe the results you observe instead of the expected results.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error logs
      description: |
       If you observe an error, please paste the error message including the **full** traceback of the exception.
      placeholder: |
        ```
        The error message you got, with the full traceback.
        ```
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."