name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install pytest-cov codecov

    - name: Run tests with coverage
      env:
        PROJECT_TEST_ENV: "1"
        OPENAI_API_KEY: "sk-mock-key-for-testing"
        API_ENDPOINT_KEY: "mock-llama-api-key-for-testing"
      run: |
        pytest --cov=synthetic_data_kit --cov-report=xml tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false