name: CI with Coverage

on:
  push:
    branches: [ main, multi ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov codecov

    - name: Lint code
      run: |
        pip install black>=25.1.0 isort>=6.0.0
        black --check synthetic_data_kit tests
        isort --check-only --profile black synthetic_data_kit tests

    - name: Run tests with coverage
      run: |
        pytest --cov=synthetic_data_kit --cov-report=xml tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false